config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :pages, :conditions => { :is_client_domain => true }

  map.resource :session, :controller => 'session', :conditions => { :is_client_domain => true }

  map.login '/login', :controller => "session", :action => 'new', :conditions => { :is_client_domain => true }
  map.logout '/logout', :controller => 'session', :action => 'destroy', :conditions => { :is_client_domain => true }

  map.resource :subscription, :controller => 'subscription', :conditions => { :is_client_domain => true }
  map.resource :billing_information, :controller => 'billing_information', :conditions => { :is_client_domain => true }

  map.upgrade '/upgrade', :controller => "subscription", :action => 'edit', :conditions => { :is_client_domain => true }

  map.resources :communities, :conditions => { :is_client_domain => false }
  map.communities '/communities', :controller => "communities", :action => 'index', :conditions => { :is_client_domain => true }
  map.communities_activate '/communities/toggle_activation/:id', :controller => "communities", :action => 'toggle_activation', :conditions => { :is_client_domain => true }

  map.setup '/getting-started/:action/:id', :controller => "setup", :conditions => { :is_client_domain => false }

  map.with_options :controller => "communities", :conditions => { :is_client_domain => true } do |pages|
    pages.community_home              '',                   :action => 'current_community_home'
    pages.community_about             '/about',             :action => 'current_community_about'
    pages.community_contact           '/contact',           :action => 'current_community_contact'
    pages.community_tos               '/tos',               :action => 'current_community_tos'
    pages.community_upsell            '/thankyou',          :action => 'current_community_upsell'
    pages.community_need_to_activate  '/need_to_activate',  :action => 'need_to_activate'
  end

  map.signup '/signup', :controller => 'users', :action => 'signup', :conditions => { :is_client_domain => true }
  map.status '/status', :controller => 'home', :action => 'status', :conditions => { :is_client_domain => false }

  map.resources :subscription_payments, :conditions => { :is_client_domain => true }

  map.resources :users, :as => 'members', :member => { :email => :any, :edit_password => :any, :disable => :any, :reactivate => :any }, :conditions => { :is_client_domain => true } do |users|
    users.resources :subscription_payments, :conditions => { :is_client_domain => true }
  end

  map.forgot_password '/forgot_password', :controller => 'users', :action => 'forgot_password', :conditions => { :is_client_domain => true }

  # the shallow nested route for discussions below doesn't give us discussions_path, only discussion_path.
  # Similarly, we don't get new_discussion_path, only new_theme_discussion_path.
  # So we need to declare those here.  This has to come before the routes below.
  map.resources :discussions, :only => [:new, :create, :index], :collection => { :uncategorized => :get }, :conditions => { :is_client_domain => true }

  map.resources :themes, :shallow => true, :collection => { :sort => :post }, :conditions => { :is_client_domain => true } do |themes|
    themes.resources :discussions, :conditions => { :is_client_domain => true } do |discussions|
      discussions.resources :responses, :conditions => { :is_client_domain => true }
      discussions.resources :email_subscriptions, :conditions => { :is_client_domain => true }
    end
  end

  map.resources :courses, :shallow => true, :collection => { :sort => :post }, :conditions => { :is_client_domain => true } do |courses|
    courses.resources :chapters, :collection => { :sort => :post }, :conditions => { :is_client_domain => true } do |chapters|
      chapters.resources :lessons, :collection => { :sort => :post }, :conditions => { :is_client_domain => true } do |lessons|
        lessons.resources :attachments, :conditions => { :is_client_domain => true }
      end
    end
  end

  map.resources :attachments, :conditions => { :is_client_domain => true }

  map.search '/search', :controller=>"search", :action=>"index", :conditions => { :is_client_domain => true }

  map.root :controller => "home", :conditions => { :is_client_domain => false }

  map.edit_community '/community/edit', :controller => 'admin', :action => 'edit_community', :conditions => { :is_client_domain => true }
  map.access_levels '/community/access', :controller => 'admin', :action => 'access_levels', :conditions => { :is_client_domain => true }
  map.create_access_level '/community/create_access', :controller => 'admin', :action => 'create_access_level', :conditions => { :is_client_domain => true }
  map.select_exported_users '/community/select_exported_users', :controller => 'admin', :action => 'select_exported_users', :conditions => { :is_client_domain => true }
  map.select_affiliate_reports '/community/affiliate_reporting', :controller => 'admin', :action => 'select_affiliate_reports', :conditions => { :is_client_domain => true }

  map.export_users '/community/export_users', :controller => 'admin', :action => 'export_users', :conditions => { :is_client_domain => true }
  map.export_users '/community/export_affiliates', :controller => 'admin', :action => 'export_affiliates', :conditions => { :is_client_domain => true }

  map.resources :access_classes, :member => { :toggle => :post }, :conditions => { :is_client_domain => true } do |access_classes|
    access_classes.resources :subscription_plans, :member => { :toggle => :post }, :conditions => { :is_client_domain => true }
  end
  
  map.media_upload '/media/:id/upload', :controller => 'media', :action => 'upload'
  map.media_done '/media/:id/done', :controller => 'media', :action => 'done'
  map.media_status '/media/:id/status', :controller => 'media', :action => 'status', :conditions => { :method => :post }
  map.update_status '/media/:id/update_status', :controller => 'media', :action => 'update_status', :conditions => { :method => :put }
  
  
  map.library '/library', :controller => 'articles', :action => 'index', :conditions => { :is_client_domain => true }
  map.resources :articles, :collection => { :sort => :post }, :conditions => { :is_client_domain => true }
  map.resources :categories, :collection => { :sort => :post }, :conditions => { :is_client_domain => true }
  
  map.catch_all '*path', :controller => 'pages', :action => 'catchall'
end

app/models/content.rb
class Content < ActiveRecord::Base
  has_one :lesson
  has_one :article
  belongs_to :user
  has_many :attachments, :dependent => :destroy
  has_many :content_access_classes, :dependent => :destroy
  has_many :access_classes, :through => :content_access_classes

  attr_accessor :uploaded_attachment_data
  validates_presence_of :title, :body, :teaser

  alias_attribute :to_s, :title
  after_save :remove_old_embedded_media
  before_save :remove_bad_embedded_media

  # Adding an association with the user's community so that we can filter on community
  is_indexed :fields => ['title', 'body', 'teaser', 'draft'], :include => [{:association_name => 'user', :field => 'community_id'}]

  def community
    return article.community unless article.nil?
    return lesson.community unless lesson.nil?
    return nil
  end

  def content_attachments=(it)
    for attachment in it
      if(!attachment.blank?)
        the_attachment = Attachment.new
        the_attachment.uploaded_data = attachment
        self.attachments << the_attachment unless it.to_s.blank?
      end
    end
  end

  def embedded_media=(file)
    unless file.to_s.blank?
      @old_embedded_media = self.attachments.find_by_embedded(true) unless @old_embedded_media
      #not sure if bad is neccessary
      @bad_embedded_media = @new_embedded_media if @new_embedded_media
      @new_embedded_media = Attachment.new
      @new_embedded_media.uploaded_data = file
      @new_embedded_media.embedded = true
      self.attachments << @new_embedded_media
    end
  end

  def display_attachments
    extensions = {}
    attachments.to_a.each do |attachment|
      unless attachment.embedded?
        extension = attachment.filename.split(".").last
        if extensions[extension].blank?
          extensions[extension] = 1
        elsif
          extensions[extension] += 1
        end
      end
    end
    strings = []
    extensions.keys.each do |extension|
      num = extensions[extension]
      strings << ((num > 1) ? num.to_s + "-" : "") + extension
    end
    return strings * ", "
  end

  def teaser_text
    self.teaser + "<br/>" + self.body.slice(0,300) + "...";
  end
  
  # Returns true if this content belongs to an article
  def article_content?
    !article.nil?
  end
  
  # Returns true if this content belongs to a lesson/course
  def lesson_content?
    !lesson.nil?
  end

  private

  def remove_old_embedded_media
    @old_embedded_media.destroy if @old_embedded_media
  end

  def remove_bad_embedded_media
    #not sure if bad is neccessary
    @bad_embedded_media.destroy if @bad_embedded_media
  end
end

app/views/contents/_edit_content.html.erb
<% content_for :head do %>
	<%= javascript_include_tag('jquery.livequery') %>
	<%= javascript_include_tag('edit') %>
	<%= javascript_include_tag('content') %>
<% end %>

<%#
  This gets copied for each iteration of form_for... not a good practice
  however, neccessary because we use f.file_field in the ruby of addAttachment
  if we could find a way to pass that information in we could not copy
  pass it in as a string?  since we use it as a string anyway...
%>
<script type="text/javascript">
removeAttachment = function(removeButton) {
	$(removeButton).up().remove();
}

addAttachment = function() {
    //need to change so that there is no bottom margin for GUI goodness
	var host = $('attachments');
    var editor = document.createElement('span');
	editor.innerHTML =
	    '<%= file_field_tag "content[content_attachments][]", :class => "formField" %>' +
    	'<input type="button" value="Remove" onclick="removeAttachment(this)" />';
	host.appendChild(editor);
}

</script>
<% fields_for content do |f| %>  
<% 	#create a list of objects if they aren't null to do error_messages_for on
	objects = []
	objects << content if content
	objects << content.attachments if content.attachments
%>
<%= error_messages_for(:content, :object => objects) %>

<fieldset class="input">

	<div class="inp group">
		<%= f.label(:title, 'Title') %>
		<%= f.text_field :title, :class => "inp_text" %>		
	</div>

	<div class="inp group">
		<%= f.label(:author, 'Author') %>
		<%= f.text_field :author, :class => "inp_text" %>
	</div>

	<div class="inp group">
		<%= f.label(:teaser, "Teaser") %>
		<%= f.text_area(:teaser, :rows => 7, :cols => 66, :class => "inp_area") %>
	</div>

	<div class="inp group">
		<%= f.label(:body, 'Body') %>
		<%= f.text_area(:body, :rows => 25, :cols => 66, :mce_editable => "true", :class => "inp_area large mceEditor") %>
	</div>

	<div class="columns">
			<h3 class="separator">Embedded Audio &amp; Video</h3>
			<p>Audio and video uploaded here will be embedded in the lesson.</p>
			<%= f.file_field :embedded_media, :size => 17, :class => "inp_file" %>
	</div>

  <h3 class="separator">Attachments</h3>
	<ul class="attachments_list attachment">
	</ul>
	<ul class="attachments_add attachment repeatable clearsub">
		<li class="create">
			<%= file_field_tag "content[content_attachments][]", :size => 17, :class => "inp_file wide" %>
		</li>
	</ul>


	<h3 class="separator">Lesson Publishing</h3>
	<ul class="checkbox group">
		<li>
			<%= f.check_box :draft %>
			<%= f.label :draft, 'Draft?' %>
		</li>
	</ul>
	<ul class="checkbox group">
		<li>
			<%= f.radio_button :registered, "false", :id => 'content_public' %>
			<%= f.label :registered, 'Public' %>
		</li>
		<li>
			<%= f.radio_button :registered, "true", :id => 'content_registered' %>
			<%= f.label :registered, 'Registered' %>
		</li>
  </ul>
  <h3 class="separator">If Registered, Limit Access to These Members:</h3>
	<ul class="checkbox group">
	  <%= hidden_field_tag "content[access_class_ids][]", "" %>
		<% current_community.access_classes.each do |access_class|%>
		<li>
		  <%= check_box_tag "content[access_class_ids][]", access_class.id, content.access_classes.include?(access_class), :class => "content_access_class" %>
			<%= label_tag "content[access_class_ids][]", access_class.name %>
		</li>
		<% end %>
	</ul>

</fieldset>
<% end %>

app/views/contents/_show_attachments.html.erb
<% show_embedded = !content.attachments.find_all_by_embedded(true).blank? && logged_in_as_owner?%>
<% show_attachments = !content.attachments.find_all_by_embedded(false).blank? %>

<% if show_embedded || show_attachments %>
	<div class="module attachments eclear">
		<div class="content">
			<% if show_attachments %>
			<h4><span>Attachments</span></h4>
			<ul class="attachments_list attachment">
				<% content.attachments.find_all_by_embedded(false).each do |attachment| %>
				<li class="media <%= attachment.type %>">
				    <%= link_to attachment.filename, attachment.authenticated_s3_url(:expires_in => 2.hours) %>
				    <% if logged_in_as_owner? %>
				    <%= link_to("Delete", attachment, :class => "action delete", :method => :delete, :confirm => "Are you sure you'd like to delete this attachment?", :return_to=> request.request_uri ) %>
				    <% end %>
				</li>
				<% end %>	
			</ul>
			<% end %>
	
			<% if show_embedded %>
			<h4>Embedded Media</h4>
			<ul class="attachments_list attachment">
				<% content.attachments.find_all_by_embedded(true).each do |attachment| %>
				<li class="media <%= attachment.type %>">
				    <%= link_to attachment.filename, attachment.url %>
				    <%= link_to("Delete", attachment, :class => "action delete", :method => :delete, :confirm => "Are you sure you'd like to delete this attachment?", :return_to=> request.request_uri ) %>
				</li>
				<% end %>
			</ul>
			<% end %>
		</div>
	</div>
<% end %>

app/views/contents/_show_content.html.erb
<div class="title">
	<h2><%=h content %></h2>
	<ul class="meta_info clear">
		<li class="date first"><%= content.updated_at.to_s(:day_month_year) %></li>
		<% if content.article && content.article.categories.size > 0 %>
		<li class="theme">
			<% content.article.reload%>
			<% content.article.categories.each do |article_category| %>
			  <%= link_to article_category, library_url(:category => article_category) %><%= ", " if article_category != content.article.categories.last %>
			<% end %>
		</li>
		<% end %>
		<% unless content.author.blank? %>
		<li class="author"><%= content.author %></li>
		<% end %>
		<li class="meta_tags">
			<ul>
				<%= content_notes(content) %>
			</ul>
		</li>
	</ul>
</div>
<% if content.lesson && logged_in_as_owner? %>
	<div class="module actions">
		<div class="content">
			<h4>Lesson Actions</h4>
			<ul class="action_nav">
				<li class="edit"><%= link_to("Edit <span class='action_target'>Lesson</span>", edit_lesson_url(@lesson))  if logged_in_as_owner? %></li>
				<li class="delete"><%= link_to("Delete <span class='action_target'>Lesson</span>", lesson_url(@lesson), :method => :delete, :confirm =>  "Are you sure you would like to delete this lesson?")  if logged_in_as_owner? %></li>
			</ul>
		</div>
	</div>
<% end %>
<% if content.article && logged_in_as_owner? %>
	<div class="module actions">
		<div class="content">
			<h4>Article Actions</h4>
			<ul class="action_nav">
				<li class="edit"><%= link_to "Edit <span class='action_target'>Article</span>", edit_article_url(@article)  if logged_in_as_owner? %></li>
				<li class="delete"><%= link_to("Delete <span class='action_target'>Article</span>", article_url(@article), :method => :delete, :confirm =>  "Are you sure you would like to delete this article?")  if logged_in_as_owner? %></li>
			</ul>
		</div>
	</div>
<% end %>
<div class="intro">
	<p><%= teaser_format(content.teaser) %></p>
</div>
<% if (embedded_media = content.attachments.find_by_embedded(true)) %>
	<% embedded_media_url = embedded_media.url %>
	<div class="module video">
	  <% if embedded_media.encoding_successful? -%>
  		<% if embedded_media.image? %>
  		<img src="<%= embedded_media_url %>" />
  		<% elsif embedded_media.legacy_video? %>
  		<div id="player<%=embedded_media.id%>">
  			This text will be replaced
  		</div>
  		<script type="text/javascript">
  			var so = new SWFObject('/mediaplayer.swf', 'mpl', '510', '500', '9');
  			so.addParam('allowfullscreen', 'true');
  			so.addParam('allowscriptaccess', 'true');
  			so.addVariable('width', '510');
  			so.addVariable('height', '500');
  			so.addVariable('file', encodeURIComponent('<%= embedded_media_url %>'));
  			so.addVariable('type', 'video');
  			so.addVariable('autostart', 'false');
  			so.write('player<%= embedded_media.id%>');
  		</script>
  		<% elsif embedded_media.video? %>
  		  <%= embedded_media.panda_embed_js %>
  		<% elsif embedded_media.audio? %>
  		<div id="player<%=embedded_media.id%>">
  		This text will be replaced
  		</div>
  		<script type="text/javascript">
  			var so = new SWFObject('/mediaplayer.swf', 'mpl', '510', '20', '9');
  			so.addParam('allowfullscreen', 'false');
  			so.addParam('allowscriptaccess', 'true');
  			so.addVariable('width', '510');
  			so.addVariable('height', '20');
  			so.addVariable('file', encodeURIComponent('<%= embedded_media_url %>'));
  			so.addVariable('type', 'sound');
  			so.addVariable('autostart', 'false');
  			so.write('player<%= embedded_media.id%>');
  		</script>
  		<% end %>
  	<% elsif embedded_media.encoding_failed? -%>
  	  <p>There was an error processing your video. Please contact Thoughtlead support for assistance.</p>
  	<% elsif embedded_media.processing? -%>
  	  	  <p>We're hard at work processing this video!</p>
  	<% end -%>
	</div>
	<div style="clear:both">&nbsp;</div>
<% end %>
<p><%= auto_link(content.body) %></p>